import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Component/Header";
import Footer from "@/Component/Footer";
import ProductContext from "@/Context/ProductContext";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Book Hub",
  description: "Generated by create next app",
  icons: {
    icon: "/ebooklogo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <GoogleOAuthProvider clientId="1095369934913-trtvgqjoaaaj0af07mhte6idgj20jdgg.apps.googleusercontent.com">
          <ProductContext>
            <Header />
            {children}
            <Footer />
          </ProductContext>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
